package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * Addresses generated by hbm2java
 */
public class Addresses implements java.io.Serializable {

	private Integer id;
//	private Integer contactId;
	private String address;
	private String surburb;
	private String postcode;
	private String state;
	private String country;
	private Contacts contact;

	public Addresses() {
	}

	public Addresses(String address, String surburb,
			String postcode, String state, String country) {
//		this.contactId = contactId;
		this.address = address;
		this.surburb = surburb;
		this.postcode = postcode;
		this.state = state;
		this.country = country;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	public Integer getContactId() {
//		return this.contactId;
//	}
//
//	public void setContactId(Integer contactId) {
//		this.contactId = contactId;
//	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSurburb() {
		return this.surburb;
	}

	public void setSurburb(String surburb) {
		this.surburb = surburb;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	
	public Contacts getContact() {
		return contact;
	}

	public void setContact(Contacts contact) {
		this.contact = contact;
	}

}
