package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AddressesHistories generated by hbm2java
 */
public class AddressesHistories implements java.io.Serializable {

	private Integer id;
	private int addressId;
	private String action;
	private String oldAddress;
	private String newAddress;
	private String oldSurburb;
	private String newSurburb;
	private String oldPostcode;
	private String newPostcode;
	private String oldState;
	private String newState;
	private String oldCountry;
	private String newCountry;
	private int createdUserId;
	private Date createdDateTime;

	public AddressesHistories() {
	}

	public AddressesHistories(int addressId, String action, int createdUserId,
			Date createdDateTime) {
		this.addressId = addressId;
		this.action = action;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	public AddressesHistories(int addressId, String action, String oldAddress,
			String newAddress, String oldSurburb, String newSurburb,
			String oldPostcode, String newPostcode, String oldState,
			String newState, String oldCountry, String newCountry,
			int createdUserId, Date createdDateTime) {
		this.addressId = addressId;
		this.action = action;
		this.oldAddress = oldAddress;
		this.newAddress = newAddress;
		this.oldSurburb = oldSurburb;
		this.newSurburb = newSurburb;
		this.oldPostcode = oldPostcode;
		this.newPostcode = newPostcode;
		this.oldState = oldState;
		this.newState = newState;
		this.oldCountry = oldCountry;
		this.newCountry = newCountry;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getOldAddress() {
		return this.oldAddress;
	}

	public void setOldAddress(String oldAddress) {
		this.oldAddress = oldAddress;
	}

	public String getNewAddress() {
		return this.newAddress;
	}

	public void setNewAddress(String newAddress) {
		this.newAddress = newAddress;
	}

	public String getOldSurburb() {
		return this.oldSurburb;
	}

	public void setOldSurburb(String oldSurburb) {
		this.oldSurburb = oldSurburb;
	}

	public String getNewSurburb() {
		return this.newSurburb;
	}

	public void setNewSurburb(String newSurburb) {
		this.newSurburb = newSurburb;
	}

	public String getOldPostcode() {
		return this.oldPostcode;
	}

	public void setOldPostcode(String oldPostcode) {
		this.oldPostcode = oldPostcode;
	}

	public String getNewPostcode() {
		return this.newPostcode;
	}

	public void setNewPostcode(String newPostcode) {
		this.newPostcode = newPostcode;
	}

	public String getOldState() {
		return this.oldState;
	}

	public void setOldState(String oldState) {
		this.oldState = oldState;
	}

	public String getNewState() {
		return this.newState;
	}

	public void setNewState(String newState) {
		this.newState = newState;
	}

	public String getOldCountry() {
		return this.oldCountry;
	}

	public void setOldCountry(String oldCountry) {
		this.oldCountry = oldCountry;
	}

	public String getNewCountry() {
		return this.newCountry;
	}

	public void setNewCountry(String newCountry) {
		this.newCountry = newCountry;
	}

	public int getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(int createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
