package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * Addresses generated by hbm2java
 */
public class Addresses implements java.io.Serializable {

	private Integer id;
	private String address;
	private String surburb;
	private String postcode;
	private String state;
	private String country;
	private String homephone;
	private Contacts contact;

	public Addresses() {
	}

	/**
	 * @param id
	 * @param address
	 * @param surburb
	 * @param postcode
	 * @param state
	 * @param country
	 * @param homephone
	 * @param contact
	 */
	public Addresses(Integer id, String address, String surburb,
			String postcode, String state, String country, String homephone,
			Contacts contact) {
		this.id = id;
		this.address = address;
		this.surburb = surburb;
		this.postcode = postcode;
		this.state = state;
		this.country = country;
		this.homephone = homephone;
		this.contact = contact;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSurburb() {
		return this.surburb;
	}

	public void setSurburb(String surburb) {
		this.surburb = surburb;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	
	/**
	 * @return the homephone
	 */
	public String getHomephone() {
		return this.homephone;
	}

	/**
	 * @param homephone the homephone to set
	 */
	public void setHomephone(String homephone) {
		this.homephone = homephone;
	}

	public Contacts getContact() {
		return this.contact;
	}

	public void setContact(Contacts contact) {
		this.contact = contact;
	}

}
