package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * CaseIssuesHistories generated by hbm2java
 * 
 * @author Kim To
 */
public class CaseIssuesHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer caseIssueId;
	private Integer caseId;
	private Integer issueTypeId;
	private String comments;
	private Integer statusId;
	private Date completedDate;
	private Integer changeOrder;
	private Integer createdUserId;
	private Integer createdDateTime;

	public CaseIssuesHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param caseIssueId
	 * @param caseId
	 * @param issueTypeId
	 * @param comments
	 * @param statusId
	 * @param completedDate
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public CaseIssuesHistories(Integer id, String action, Integer caseIssueId,
			Integer caseId, Integer issueTypeId, String comments,
			Integer statusId, Date completedDate, Integer changeOrder,
			Integer createdUserId, Integer createdDateTime) {
		this.id = id;
		this.action = action;
		this.caseIssueId = caseIssueId;
		this.caseId = caseId;
		this.issueTypeId = issueTypeId;
		this.comments = comments;
		this.statusId = statusId;
		this.completedDate = completedDate;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the caseIssueId
	 */
	public Integer getCaseIssueId() {
		return this.caseIssueId;
	}

	/**
	 * @param caseIssueId the caseIssueId to set
	 */
	public void setCaseIssueId(Integer caseIssueId) {
		this.caseIssueId = caseIssueId;
	}

	/**
	 * @return the caseId
	 */
	public Integer getCaseId() {
		return this.caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the issueTypeId
	 */
	public Integer getIssueTypeId() {
		return this.issueTypeId;
	}

	/**
	 * @param issueTypeId the issueTypeId to set
	 */
	public void setIssueTypeId(Integer issueTypeId) {
		this.issueTypeId = issueTypeId;
	}

	/**
	 * @return the comments
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * @param comments the comments to set
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * @return the statusId
	 */
	public Integer getStatusId() {
		return this.statusId;
	}

	/**
	 * @param statusId the statusId to set
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * @return the completedDate
	 */
	public Date getCompletedDate() {
		return this.completedDate;
	}

	/**
	 * @param completedDate the completedDate to set
	 */
	public void setCompletedDate(Date completedDate) {
		this.completedDate = completedDate;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Integer getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Integer createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
