package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CaseIssues generated by hbm2java
 */
public class CaseIssues implements java.io.Serializable {

	private Integer id;
	private Integer caseId;
	private Integer issueTypeId;
	private String comments;
	private Integer statusId;
	private Date completedDate;
	private Date createdDate;
	private Integer createdUserId;

	public CaseIssues() {
	}

	public CaseIssues(Integer caseId, Integer issueTypeId, String comments,
			Integer statusId, Date completedDate, Date createdDate,
			Integer createdUserId) {
		this.caseId = caseId;
		this.issueTypeId = issueTypeId;
		this.comments = comments;
		this.statusId = statusId;
		this.completedDate = completedDate;
		this.createdDate = createdDate;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Integer getIssueTypeId() {
		return this.issueTypeId;
	}

	public void setIssueTypeId(Integer issueTypeId) {
		this.issueTypeId = issueTypeId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public Date getCompletedDate() {
		return this.completedDate;
	}

	public void setCompletedDate(Date completedDate) {
		this.completedDate = completedDate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

}
