package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CaseIssues generated by hbm2java
 */
public class CaseIssues implements java.io.Serializable {

	private Integer id;
//	private Integer caseId;
//	private Integer issueTypeId;
	private IndividualCases individualCase;
	private IssueTypes issue;
	private String comments;
//	private Integer statusId;
	private StatusTypes statusType;
	private Date completedDate;
	private Date createdDate;
	private Integer createdUserId;

	public CaseIssues() {
	}


	/**
	 * @param id
	 * @param individualCase
	 * @param issue
	 * @param comments
	 * @param statusType
	 * @param completedDate
	 * @param createdDate
	 * @param createdUserId
	 */
	public CaseIssues(Integer id, IndividualCases individualCase,
			IssueTypes issue, String comments, StatusTypes statusType,
			Date completedDate, Date createdDate, Integer createdUserId) {
		this.id = id;
		this.individualCase = individualCase;
		this.issue = issue;
		this.comments = comments;
		this.statusType = statusType;
		this.completedDate = completedDate;
		this.createdDate = createdDate;
		this.createdUserId = createdUserId;
	}




	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	public Integer getCaseId() {
//		return this.caseId;
//	}
//
//	public void setCaseId(Integer caseId) {
//		this.caseId = caseId;
//	}
//
//	public Integer getIssueTypeId() {
//		return this.issueTypeId;
//	}
//
//	public void setIssueTypeId(Integer issueTypeId) {
//		this.issueTypeId = issueTypeId;
//	}

	/**
	 * @return the individualCase
	 */
	public IndividualCases getIndividualCase() {
		return individualCase;
	}


	/**
	 * @param individualCase the individualCase to set
	 */
	public void setIndividualCase(IndividualCases individualCase) {
		this.individualCase = individualCase;
	}


	/**
	 * @return the issue
	 */
	public IssueTypes getIssue() {
		return issue;
	}


	/**
	 * @param issue the issue to set
	 */
	public void setIssue(IssueTypes issue) {
		this.issue = issue;
	}


	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

//	public Integer getStatusId() {
//		return this.statusId;
//	}
//
//	public void setStatusId(Integer statusId) {
//		this.statusId = statusId;
//	}

	/**
	 * @return the statusType
	 */
	public StatusTypes getStatusType() {
		return statusType;
	}


	/**
	 * @param statusType the statusType to set
	 */
	public void setStatusType(StatusTypes statusType) {
		this.statusType = statusType;
	}


	public Date getCompletedDate() {
		return this.completedDate;
	}

	public void setCompletedDate(Date completedDate) {
		this.completedDate = completedDate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

}
