package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * ClientDisabilitiesHistories generated by hbm2java
 */
public class ClientDisabilitiesHistories implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private int clientDisabilityId;
	private String action;
	private Integer contactId;
	private Integer oldDisabilityId;
	private Integer newDisabilityId;
	private String oldComments;
	private String newComments;
	private String oldPrimaryFlag;
	private String newPrimaryFlag;
	private int createdUserId;

	public ClientDisabilitiesHistories() {
	}

	public ClientDisabilitiesHistories(int clientDisabilityId, String action,
			int createdUserId) {
		this.clientDisabilityId = clientDisabilityId;
		this.action = action;
		this.createdUserId = createdUserId;
	}

	public ClientDisabilitiesHistories(int clientDisabilityId, String action,
			Integer contactId, Integer oldDisabilityId,
			Integer newDisabilityId, String oldComments, String newComments,
			String oldPrimaryFlag, String newPrimaryFlag, int createdUserId) {
		this.clientDisabilityId = clientDisabilityId;
		this.action = action;
		this.contactId = contactId;
		this.oldDisabilityId = oldDisabilityId;
		this.newDisabilityId = newDisabilityId;
		this.oldComments = oldComments;
		this.newComments = newComments;
		this.oldPrimaryFlag = oldPrimaryFlag;
		this.newPrimaryFlag = newPrimaryFlag;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getClientDisabilityId() {
		return this.clientDisabilityId;
	}

	public void setClientDisabilityId(int clientDisabilityId) {
		this.clientDisabilityId = clientDisabilityId;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public Integer getOldDisabilityId() {
		return this.oldDisabilityId;
	}

	public void setOldDisabilityId(Integer oldDisabilityId) {
		this.oldDisabilityId = oldDisabilityId;
	}

	public Integer getNewDisabilityId() {
		return this.newDisabilityId;
	}

	public void setNewDisabilityId(Integer newDisabilityId) {
		this.newDisabilityId = newDisabilityId;
	}

	public String getOldComments() {
		return this.oldComments;
	}

	public void setOldComments(String oldComments) {
		this.oldComments = oldComments;
	}

	public String getNewComments() {
		return this.newComments;
	}

	public void setNewComments(String newComments) {
		this.newComments = newComments;
	}

	public String getOldPrimaryFlag() {
		return this.oldPrimaryFlag;
	}

	public void setOldPrimaryFlag(String oldPrimaryFlag) {
		this.oldPrimaryFlag = oldPrimaryFlag;
	}

	public String getNewPrimaryFlag() {
		return this.newPrimaryFlag;
	}

	public void setNewPrimaryFlag(String newPrimaryFlag) {
		this.newPrimaryFlag = newPrimaryFlag;
	}

	public int getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(int createdUserId) {
		this.createdUserId = createdUserId;
	}

}
