package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * ClientDisabilitiesHistories generated by hbm2java
 * 
 * @author Kim To
 */
public class ClientDisabilitiesHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer clientDisabilityId;
	private Integer contactId;
	private Integer disabilityId;
	private String comments;
	private String primaryFlag;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public ClientDisabilitiesHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param clientDisabilityId
	 * @param contactId
	 * @param disabilityId
	 * @param comments
	 * @param primaryFlag
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public ClientDisabilitiesHistories(Integer id, String action,
			Integer clientDisabilityId, Integer contactId,
			Integer disabilityId, String comments, String primaryFlag,
			Integer changeOrder, Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.clientDisabilityId = clientDisabilityId;
		this.contactId = contactId;
		this.disabilityId = disabilityId;
		this.comments = comments;
		this.primaryFlag = primaryFlag;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}


	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the clientDisabilityId
	 */
	public Integer getClientDisabilityId() {
		return this.clientDisabilityId;
	}

	/**
	 * @param clientDisabilityId the clientDisabilityId to set
	 */
	public void setClientDisabilityId(Integer clientDisabilityId) {
		this.clientDisabilityId = clientDisabilityId;
	}

	/**
	 * @return the contactId
	 */
	public Integer getContactId() {
		return this.contactId;
	}

	/**
	 * @param contactId the contactId to set
	 */
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	/**
	 * @return the disabilityId
	 */
	public Integer getDisabilityId() {
		return this.disabilityId;
	}

	/**
	 * @param disabilityId the disabilityId to set
	 */
	public void setDisabilityId(Integer disabilityId) {
		this.disabilityId = disabilityId;
	}

	/**
	 * @return the comments
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * @param comments the comments to set
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * @return the primaryFlag
	 */
	public String getPrimaryFlag() {
		return this.primaryFlag;
	}

	/**
	 * @param primaryFlag the primaryFlag to set
	 */
	public void setPrimaryFlag(String primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
