package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * ContactsHistories generated by hbm2java
 * 
 * @author Kim To
 * @version 1.0.1, 28/09/2014
 * 
 * Modification History:
 * 		28/09/2014
 * 			Mods to delete and add attributes, constructor, setters, and getters
 */
public class ContactsHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer contactId;
	private Integer titleId;
	private String firstname;
	private String lastname;
	private String othername;
	private Integer genderId;
	private Integer contactTypeId;
	private String mobilephone;
	private String email;
	private Integer accommodationId;
	private String accommodationComment;
	private Integer culturalBackgroundId;
	private String culturalBackgroundComment;
	private Integer dangerFlagId;
	private String identification;
	private Date dob;
	private Integer statusId;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public ContactsHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param contactId
	 * @param titleId
	 * @param firstname
	 * @param lastname
	 * @param othername
	 * @param genderId
	 * @param contactTypeId
	 * @param mobilephone
	 * @param email
	 * @param accommodationId
	 * @param accommodationComment
	 * @param culturalBackgroundId
	 * @param culturalBackgroundComment
	 * @param dangerFlagId
	 * @param identification
	 * @param dob
	 * @param statusId
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public ContactsHistories(Integer id, String action, Integer contactId,
			Integer titleId, String firstname, String lastname,
			String othername, Integer genderId, Integer contactTypeId,
			String mobilephone, String email, Integer accommodationId,
			String accommodationComment, Integer culturalBackgroundId,
			String culturalBackgroundComment, Integer dangerFlagId,
			String identification, Date dob, Integer statusId,
			Integer changeOrder, Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.contactId = contactId;
		this.titleId = titleId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.othername = othername;
		this.genderId = genderId;
		this.contactTypeId = contactTypeId;
		this.mobilephone = mobilephone;
		this.email = email;
		this.accommodationId = accommodationId;
		this.accommodationComment = accommodationComment;
		this.culturalBackgroundId = culturalBackgroundId;
		this.culturalBackgroundComment = culturalBackgroundComment;
		this.dangerFlagId = dangerFlagId;
		this.identification = identification;
		this.dob = dob;
		this.statusId = statusId;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}



	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the contactId
	 */
	public Integer getContactId() {
		return this.contactId;
	}

	/**
	 * @param contactId the contactId to set
	 */
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	/**
	 * @return the titleId
	 */
	public Integer getTitleId() {
		return this.titleId;
	}

	/**
	 * @param titleId the titleId to set
	 */
	public void setTitleId(Integer titleId) {
		this.titleId = titleId;
	}

	/**
	 * @return the firstname
	 */
	public String getFirstname() {
		return this.firstname;
	}

	/**
	 * @param firstname the firstname to set
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * @return the lastname
	 */
	public String getLastname() {
		return this.lastname;
	}

	/**
	 * @param lastname the lastname to set
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * @return the othername
	 */
	public String getOthername() {
		return this.othername;
	}

	/**
	 * @param othername the othername to set
	 */
	public void setOthername(String othername) {
		this.othername = othername;
	}

	/**
	 * @return the genderId
	 */
	public Integer getGenderId() {
		return this.genderId;
	}

	/**
	 * @param genderId the genderId to set
	 */
	public void setGenderId(Integer genderId) {
		this.genderId = genderId;
	}

	/**
	 * @return the contactTypeId
	 */
	public Integer getContactTypeId() {
		return this.contactTypeId;
	}

	/**
	 * @param contactTypeId the contactTypeId to set
	 */
	public void setContactTypeId(Integer contactTypeId) {
		this.contactTypeId = contactTypeId;
	}

	/**
	 * @return the mobilephone
	 */
	public String getMobilephone() {
		return this.mobilephone;
	}

	/**
	 * @param mobilephone the mobilephone to set
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the accommodationId
	 */
	public Integer getAccommodationId() {
		return this.accommodationId;
	}

	/**
	 * @param accommodationId the accommodationId to set
	 */
	public void setAccommodationId(Integer accommodationId) {
		this.accommodationId = accommodationId;
	}

	/**
	 * @return the accommodationComment
	 */
	public String getAccommodationComment() {
		return this.accommodationComment;
	}

	/**
	 * @param accommodationComment the accommodationComment to set
	 */
	public void setAccommodationComment(String accommodationComment) {
		this.accommodationComment = accommodationComment;
	}

	/**
	 * @return the culturalBackgroundId
	 */
	public Integer getCulturalBackgroundId() {
		return this.culturalBackgroundId;
	}

	/**
	 * @param culturalBackgroundId the culturalBackgroundId to set
	 */
	public void setCulturalBackgroundId(Integer culturalBackgroundId) {
		this.culturalBackgroundId = culturalBackgroundId;
	}

	/**
	 * @return the culturalBackgroundComment
	 */
	public String getCulturalBackgroundComment() {
		return this.culturalBackgroundComment;
	}

	/**
	 * @param culturalBackgroundComment the culturalBackgroundComment to set
	 */
	public void setCulturalBackgroundComment(String culturalBackgroundComment) {
		this.culturalBackgroundComment = culturalBackgroundComment;
	}

	/**
	 * @return the dangerFlagId
	 */
	public Integer getDangerFlagId() {
		return this.dangerFlagId;
	}

	/**
	 * @param dangerFlagId the dangerFlagId to set
	 */
	public void setDangerFlagId(Integer dangerFlagId) {
		this.dangerFlagId = dangerFlagId;
	}

	/**
	 * @return the identification
	 */
	public String getIdentification() {
		return this.identification;
	}

	/**
	 * @param identification the identification to set
	 */
	public void setIdentification(String identification) {
		this.identification = identification;
	}

	/**
	 * @return the dob
	 */
	public Date getDob() {
		return this.dob;
	}

	/**
	 * @param dob the dob to set
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * @return the statusId
	 */
	public Integer getStatusId() {
		return this.statusId;
	}

	/**
	 * @param statusId the statusId to set
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return this.changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
