package uow.ia.bean;

import java.util.Set;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * DangerTypes generated by hbm2java
 */
public class DangerTypes implements java.io.Serializable {

	private Integer id;
	private String dangerName;
	private String dangerDescription;
	private String symbol;
	private Integer displayOrder;
	private Set<Contacts> contactsSet;

	public DangerTypes() {
	}

	public DangerTypes(String dangerName, String dangerDescription,
			String symbol, Integer displayOrder) {
		this.dangerName = dangerName;
		this.dangerDescription = dangerDescription;
		this.symbol = symbol;
		this.displayOrder = displayOrder;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDangerName() {
		return this.dangerName;
	}

	public void setDangerName(String dangerName) {
		this.dangerName = dangerName;
	}

	public String getDangerDescription() {
		return this.dangerDescription;
	}

	public void setDangerDescription(String dangerDescription) {
		this.dangerDescription = dangerDescription;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	public Set<Contacts> getContactsSet() {
		return this.contactsSet;
	}

	public void setContactsSet(Set<Contacts> contactsSet) {
		this.contactsSet = contactsSet;
	}

}
