package uow.ia.bean;

import java.util.HashSet;
import java.util.Set;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * DisabilityTypes generated by hbm2java
 */
public class DisabilityTypes implements java.io.Serializable {

	private Integer id;
	private String disabilityName;
	private String disabilityDescription;
	private Set<ClientDisabilities> clientDisabilitiesSet = new HashSet<ClientDisabilities>();
	/**
	 * 
	 */
	public DisabilityTypes() {
	}
	
	/**
	 * @param id
	 * @param disabilityName
	 * @param disabilityDescription
	 * @param clientDisabilitiesSet
	 */
	public DisabilityTypes(Integer id, String disabilityName,
			String disabilityDescription,
			Set<ClientDisabilities> clientDisabilitiesSet) {
		this.id = id;
		this.disabilityName = disabilityName;
		this.disabilityDescription = disabilityDescription;
		this.clientDisabilitiesSet = clientDisabilitiesSet;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * @return the disabilityName
	 */
	public String getDisabilityName() {
		return this.disabilityName;
	}
	/**
	 * @param disabilityName the disabilityName to set
	 */
	public void setDisabilityName(String disabilityName) {
		this.disabilityName = disabilityName;
	}
	/**
	 * @return the disabilityDescription
	 */
	public String getDisabilityDescription() {
		return this.disabilityDescription;
	}
	/**
	 * @param disabilityDescription the disabilityDescription to set
	 */
	public void setDisabilityDescription(String disabilityDescription) {
		this.disabilityDescription = disabilityDescription;
	}

	/**
	 * @return the clientDisabilitiesSet
	 */
	public Set<ClientDisabilities> getClientDisabilitiesSet() {
		return this.clientDisabilitiesSet;
	}

	/**
	 * @param clientDisabilitiesSet the clientDisabilitiesSet to set
	 */
	public void setClientDisabilitiesSet(
			Set<ClientDisabilities> clientDisabilitiesSet) {
		this.clientDisabilitiesSet = clientDisabilitiesSet;
	}
	

}
