package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * EmploymentTypes generated by hbm2java
 */
public class EmploymentTypes implements java.io.Serializable {

	private Integer id;
	private String employmentName;
	private String employmentDescription;

	public EmploymentTypes() {
	}

	public EmploymentTypes(String employmentName, String employmentDescription) {
		this.employmentName = employmentName;
		this.employmentDescription = employmentDescription;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmploymentName() {
		return this.employmentName;
	}

	public void setEmploymentName(String employmentName) {
		this.employmentName = employmentName;
	}

	public String getEmploymentDescription() {
		return this.employmentDescription;
	}

	public void setEmploymentDescription(String employmentDescription) {
		this.employmentDescription = employmentDescription;
	}

}
