package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * EnquiryIssuesHistories generated by hbm2java
 * 
 * @author Kim To
 */
public class EnquiryIssuesHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer enquiryIssueId;
	private Integer enquiryId;
	private Integer issueId;
	private String comment;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public EnquiryIssuesHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param enquiryIssueId
	 * @param enquiryId
	 * @param issueId
	 * @param comment
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public EnquiryIssuesHistories(Integer id, String action,
			Integer enquiryIssueId, Integer enquiryId, Integer issueId,
			String comment, Integer changeOrder, Integer createdUserId,
			Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.enquiryIssueId = enquiryIssueId;
		this.enquiryId = enquiryId;
		this.issueId = issueId;
		this.comment = comment;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the enquiryIssueId
	 */
	public Integer getEnquiryIssueId() {
		return this.enquiryIssueId;
	}

	/**
	 * @param enquiryIssueId the enquiryIssueId to set
	 */
	public void setEnquiryIssueId(Integer enquiryIssueId) {
		this.enquiryIssueId = enquiryIssueId;
	}

	/**
	 * @return the enquiryId
	 */
	public Integer getEnquiryId() {
		return this.enquiryId;
	}

	/**
	 * @param enquiryId the enquiryId to set
	 */
	public void setEnquiryId(Integer enquiryId) {
		this.enquiryId = enquiryId;
	}

	/**
	 * @return the issueId
	 */
	public Integer getIssueId() {
		return this.issueId;
	}

	/**
	 * @param issueId the issueId to set
	 */
	public void setIssueId(Integer issueId) {
		this.issueId = issueId;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return this.comment;
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return this.changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
