package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * EnquiryIssuesHistories generated by hbm2java
 */
public class EnquiryIssuesHistories implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private int enquiryIssueId;
	private Integer enquiryId;
	private Integer oldIssueId;
	private Integer newIssueId;
	private String oldComment;
	private String newComment;
	private String action;
	private int createdUserId;

	public EnquiryIssuesHistories() {
	}

	public EnquiryIssuesHistories(int enquiryIssueId, String action,
			int createdUserId) {
		this.enquiryIssueId = enquiryIssueId;
		this.action = action;
		this.createdUserId = createdUserId;
	}

	public EnquiryIssuesHistories(int enquiryIssueId, Integer enquiryId,
			Integer oldIssueId, Integer newIssueId, String oldComment,
			String newComment, String action, int createdUserId) {
		this.enquiryIssueId = enquiryIssueId;
		this.enquiryId = enquiryId;
		this.oldIssueId = oldIssueId;
		this.newIssueId = newIssueId;
		this.oldComment = oldComment;
		this.newComment = newComment;
		this.action = action;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getEnquiryIssueId() {
		return this.enquiryIssueId;
	}

	public void setEnquiryIssueId(int enquiryIssueId) {
		this.enquiryIssueId = enquiryIssueId;
	}

	public Integer getEnquiryId() {
		return this.enquiryId;
	}

	public void setEnquiryId(Integer enquiryId) {
		this.enquiryId = enquiryId;
	}

	public Integer getOldIssueId() {
		return this.oldIssueId;
	}

	public void setOldIssueId(Integer oldIssueId) {
		this.oldIssueId = oldIssueId;
	}

	public Integer getNewIssueId() {
		return this.newIssueId;
	}

	public void setNewIssueId(Integer newIssueId) {
		this.newIssueId = newIssueId;
	}

	public String getOldComment() {
		return this.oldComment;
	}

	public void setOldComment(String oldComment) {
		this.oldComment = oldComment;
	}

	public String getNewComment() {
		return this.newComment;
	}

	public void setNewComment(String newComment) {
		this.newComment = newComment;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public int getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(int createdUserId) {
		this.createdUserId = createdUserId;
	}

}
