package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * EnquiryTypes generated by hbm2java
 */
public class EnquiryTypes implements java.io.Serializable {

	private Integer id;
	private String enquiryTypeName;
	private String enquiryTypeDescription;

	public EnquiryTypes() {
	}

	public EnquiryTypes(String enquiryTypeName) {
		this.enquiryTypeName = enquiryTypeName;
	}

	public EnquiryTypes(String enquiryTypeName, String enquiryTypeDescription) {
		this.enquiryTypeName = enquiryTypeName;
		this.enquiryTypeDescription = enquiryTypeDescription;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEnquiryTypeName() {
		return this.enquiryTypeName;
	}

	public void setEnquiryTypeName(String enquiryTypeName) {
		this.enquiryTypeName = enquiryTypeName;
	}

	public String getEnquiryTypeDescription() {
		return this.enquiryTypeDescription;
	}

	public void setEnquiryTypeDescription(String enquiryTypeDescription) {
		this.enquiryTypeDescription = enquiryTypeDescription;
	}

}
