package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * EnquiriesHistories generated by hbm2java
 * 
 * @author Kim To
 * @version 1.0.1, 28/09/2014
 * 
 * Modification History:
 * 		28/09/2014 - Delete and add attributes to match table structure
 * 					 Mods to constructor, setters, and getters
 */
public class EnquiriesHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer enquiryId;
	private Integer contactId;
	private Integer enquiryTypeId;
	private Integer statusId;
	private String description;
	private String inquisitor;
	private String referralBy;
	private String referralTo;
	private Integer parentEnquiryId;
	private String outOfCoverageFlag;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public EnquiriesHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param enquiryId
	 * @param contactId
	 * @param enquiryTypeId
	 * @param statusId
	 * @param description
	 * @param inquisitor
	 * @param referralBy
	 * @param referralTo
	 * @param parentEnquiryId
	 * @param outOfCoverageFlag
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public EnquiriesHistories(Integer id, String action, Integer enquiryId,
			Integer contactId, Integer enquiryTypeId, Integer statusId,
			String description, String inquisitor, String referralBy,
			String referralTo, Integer parentEnquiryId,
			String outOfCoverageFlag, Integer changeOrder,
			Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.enquiryId = enquiryId;
		this.contactId = contactId;
		this.enquiryTypeId = enquiryTypeId;
		this.statusId = statusId;
		this.description = description;
		this.inquisitor = inquisitor;
		this.referralBy = referralBy;
		this.referralTo = referralTo;
		this.parentEnquiryId = parentEnquiryId;
		this.outOfCoverageFlag = outOfCoverageFlag;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the enquiryId
	 */
	public Integer getEnquiryId() {
		return enquiryId;
	}

	/**
	 * @param enquiryId the enquiryId to set
	 */
	public void setEnquiryId(Integer enquiryId) {
		this.enquiryId = enquiryId;
	}

	/**
	 * @return the contactId
	 */
	public Integer getContactId() {
		return contactId;
	}

	/**
	 * @param contactId the contactId to set
	 */
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	/**
	 * @return the enquiryTypeId
	 */
	public Integer getEnquiryTypeId() {
		return enquiryTypeId;
	}

	/**
	 * @param enquiryTypeId the enquiryTypeId to set
	 */
	public void setEnquiryTypeId(Integer enquiryTypeId) {
		this.enquiryTypeId = enquiryTypeId;
	}

	/**
	 * @return the statusId
	 */
	public Integer getStatusId() {
		return statusId;
	}

	/**
	 * @param statusId the statusId to set
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the inquisitor
	 */
	public String getInquisitor() {
		return inquisitor;
	}

	/**
	 * @param inquisitor the inquisitor to set
	 */
	public void setInquisitor(String inquisitor) {
		this.inquisitor = inquisitor;
	}

	/**
	 * @return the referralBy
	 */
	public String getReferralBy() {
		return referralBy;
	}

	/**
	 * @param referralBy the referralBy to set
	 */
	public void setReferralBy(String referralBy) {
		this.referralBy = referralBy;
	}

	/**
	 * @return the referralTo
	 */
	public String getReferralTo() {
		return referralTo;
	}

	/**
	 * @param referralTo the referralTo to set
	 */
	public void setReferralTo(String referralTo) {
		this.referralTo = referralTo;
	}

	/**
	 * @return the parentEnquiryId
	 */
	public Integer getParentEnquiryId() {
		return parentEnquiryId;
	}

	/**
	 * @param parentEnquiryId the parentEnquiryId to set
	 */
	public void setParentEnquiryId(Integer parentEnquiryId) {
		this.parentEnquiryId = parentEnquiryId;
	}

	/**
	 * @return the outOfCoverageFlag
	 */
	public String getOutOfCoverageFlag() {
		return outOfCoverageFlag;
	}

	/**
	 * @param outOfCoverageFlag the outOfCoverageFlag to set
	 */
	public void setOutOfCoverageFlag(String outOfCoverageFlag) {
		this.outOfCoverageFlag = outOfCoverageFlag;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
