package uow.ia.bean;

import java.util.HashSet;
import java.util.Set;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * EnquiryIssues generated by hbm2java
 */
public class EnquiryIssues implements java.io.Serializable {

	private Integer id;
//	private Integer enquiryId;
//	private Integer issueId;
	private Enquiries enquiry;
	private IssueTypes issue;
	private String comment;
	/**
	 * 
	 */
	public EnquiryIssues() {
		// TODO Auto-generated constructor stub
	}
	/**
	 * @param id
	 * @param enquiry
	 * @param issue
	 * @param comment
	 */
	public EnquiryIssues(Integer id, Enquiries enquiry, IssueTypes issue,
			String comment) {
		this.id = id;
		this.enquiry = enquiry;
		this.issue = issue;
		this.comment = comment;
	}
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}
/**
	 * @return the enquiry
	 */
	public Enquiries getEnquiry() {
		return this.enquiry;
	}
	/**
	 * @param enquiry the enquiry to set
	 */
	public void setEnquiry(Enquiries enquiry) {
		this.enquiry = enquiry;
	}
	/**
	 * @return the issue
	 */
	public IssueTypes getIssue() {
		return this.issue;
	}
	/**
	 * @param issue the issue to set
	 */
	public void setIssue(IssueTypes issue) {
		this.issue = issue;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return this.comment;
	}
	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

}
