package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

import org.hibernate.search.annotations.DateBridge;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Resolution;

/**
 * Events generated by hbm2java
 * 
 * @author KimTo
 */

@Indexed
public class Events implements java.io.Serializable {

	@DocumentId
	private Integer id;
	
	@DateBridge(resolution = Resolution.HOUR)
	@Field
	private Date startTime;
	
	@DateBridge(resolution = Resolution.HOUR)
	@Field
	private Date endTime;
	
	@DateBridge(resolution = Resolution.DAY)
	@Field
	private Date date;
	
	@Field
	private String description;
	
	@Field
	private Integer contactLinkId;
	
	@Field
	private Integer caseLinkId;
	private Date updatedDateTime;
	
	@Field
	private Integer updatedUserId;
	
	@Field
	private Integer createdUserId;
	
	@DateBridge(resolution = Resolution.DAY)
	@Field
	private Date createdDateTime;

	public Events() {
	}

	public Events(Date startTime, Date endTime, Date date, String description,
			Integer contactLinkId, Integer caseLinkId, Date updatedDateTime,
			Integer updatedUserId, Integer createdUserId, Date createdDateTime) {
		this.startTime = startTime;
		this.endTime = endTime;
		this.date = date;
		this.description = description;
		this.contactLinkId = contactLinkId;
		this.caseLinkId = caseLinkId;
		this.updatedDateTime = updatedDateTime;
		this.updatedUserId = updatedUserId;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getContactLinkId() {
		return this.contactLinkId;
	}

	public void setContactLinkId(Integer contactLinkId) {
		this.contactLinkId = contactLinkId;
	}

	public Integer getCaseLinkId() {
		return this.caseLinkId;
	}

	public void setCaseLinkId(Integer caseLinkId) {
		this.caseLinkId = caseLinkId;
	}

	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	public Integer getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Integer updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
