package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * GoalTypes generated by hbm2java
 */
public class GoalTypes implements java.io.Serializable {

	private Integer id;
	private String goalTypeName;

	public GoalTypes() {
	}

	public GoalTypes(String goalTypeName) {
		this.goalTypeName = goalTypeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGoalTypeName() {
		return this.goalTypeName;
	}

	public void setGoalTypeName(String goalTypeName) {
		this.goalTypeName = goalTypeName;
	}

}
