package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * IacaseEnquiryMappings generated by hbm2java
 */
public class IacaseEnquiryMappings implements java.io.Serializable {

	private Integer id;
	private Integer caseId;
	private Integer enquiryId;

	public IacaseEnquiryMappings() {
	}

	public IacaseEnquiryMappings(Integer caseId, Integer enquiryId) {
		this.caseId = caseId;
		this.enquiryId = enquiryId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Integer getEnquiryId() {
		return this.enquiryId;
	}

	public void setEnquiryId(Integer enquiryId) {
		this.enquiryId = enquiryId;
	}

}
