package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * IaCommunicationsHistories generated by hbm2java
 */
public class IaCommunicationsHistories implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private String action;
	private int communicationId;
	private Integer caseId;
	private Date oldCommunicationDate;
	private Date newCommunicationDate;
	private Integer oldCommunicationTypeId;
	private Integer newCommunicationTypeId;
	private String oldDescription;
	private String newDescription;
	private Float oldTimeSpent;
	private Float newTimeSpent;
	private String oldImportantFlag;
	private String newImportantFlag;
	private Integer createdUserId;

	public IaCommunicationsHistories() {
	}

	public IaCommunicationsHistories(String action, int communicationId) {
		this.action = action;
		this.communicationId = communicationId;
	}

	public IaCommunicationsHistories(String action, int communicationId,
			Integer caseId, Date oldCommunicationDate,
			Date newCommunicationDate, Integer oldCommunicationTypeId,
			Integer newCommunicationTypeId, String oldDescription,
			String newDescription, Float oldTimeSpent, Float newTimeSpent,
			String oldImportantFlag, String newImportantFlag,
			Integer createdUserId) {
		this.action = action;
		this.communicationId = communicationId;
		this.caseId = caseId;
		this.oldCommunicationDate = oldCommunicationDate;
		this.newCommunicationDate = newCommunicationDate;
		this.oldCommunicationTypeId = oldCommunicationTypeId;
		this.newCommunicationTypeId = newCommunicationTypeId;
		this.oldDescription = oldDescription;
		this.newDescription = newDescription;
		this.oldTimeSpent = oldTimeSpent;
		this.newTimeSpent = newTimeSpent;
		this.oldImportantFlag = oldImportantFlag;
		this.newImportantFlag = newImportantFlag;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public int getCommunicationId() {
		return this.communicationId;
	}

	public void setCommunicationId(int communicationId) {
		this.communicationId = communicationId;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Date getOldCommunicationDate() {
		return this.oldCommunicationDate;
	}

	public void setOldCommunicationDate(Date oldCommunicationDate) {
		this.oldCommunicationDate = oldCommunicationDate;
	}

	public Date getNewCommunicationDate() {
		return this.newCommunicationDate;
	}

	public void setNewCommunicationDate(Date newCommunicationDate) {
		this.newCommunicationDate = newCommunicationDate;
	}

	public Integer getOldCommunicationTypeId() {
		return this.oldCommunicationTypeId;
	}

	public void setOldCommunicationTypeId(Integer oldCommunicationTypeId) {
		this.oldCommunicationTypeId = oldCommunicationTypeId;
	}

	public Integer getNewCommunicationTypeId() {
		return this.newCommunicationTypeId;
	}

	public void setNewCommunicationTypeId(Integer newCommunicationTypeId) {
		this.newCommunicationTypeId = newCommunicationTypeId;
	}

	public String getOldDescription() {
		return this.oldDescription;
	}

	public void setOldDescription(String oldDescription) {
		this.oldDescription = oldDescription;
	}

	public String getNewDescription() {
		return this.newDescription;
	}

	public void setNewDescription(String newDescription) {
		this.newDescription = newDescription;
	}

	public Float getOldTimeSpent() {
		return this.oldTimeSpent;
	}

	public void setOldTimeSpent(Float oldTimeSpent) {
		this.oldTimeSpent = oldTimeSpent;
	}

	public Float getNewTimeSpent() {
		return this.newTimeSpent;
	}

	public void setNewTimeSpent(Float newTimeSpent) {
		this.newTimeSpent = newTimeSpent;
	}

	public String getOldImportantFlag() {
		return this.oldImportantFlag;
	}

	public void setOldImportantFlag(String oldImportantFlag) {
		this.oldImportantFlag = oldImportantFlag;
	}

	public String getNewImportantFlag() {
		return this.newImportantFlag;
	}

	public void setNewImportantFlag(String newImportantFlag) {
		this.newImportantFlag = newImportantFlag;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

}
