package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * IndividualCaseCommunications generated by hbm2java
 */
public class IndividualCaseCommunications implements java.io.Serializable {

	private Integer id;
	private Integer caseId;
	private Date communicationDate;
	private Integer communicationTypeId;
	private String description;
	private Integer createdUserId;
	private Date createdDateTime;
	private Float timeSpent;
	private String importantFlag;

	public IndividualCaseCommunications() {
	}

	public IndividualCaseCommunications(Integer caseId, Date communicationDate,
			Integer communicationTypeId, String description,
			Integer createdUserId, Date createdDateTime, Float timeSpent,
			String importantFlag) {
		this.caseId = caseId;
		this.communicationDate = communicationDate;
		this.communicationTypeId = communicationTypeId;
		this.description = description;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
		this.timeSpent = timeSpent;
		this.importantFlag = importantFlag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Date getCommunicationDate() {
		return this.communicationDate;
	}

	public void setCommunicationDate(Date communicationDate) {
		this.communicationDate = communicationDate;
	}

	public Integer getCommunicationTypeId() {
		return this.communicationTypeId;
	}

	public void setCommunicationTypeId(Integer communicationTypeId) {
		this.communicationTypeId = communicationTypeId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public Float getTimeSpent() {
		return this.timeSpent;
	}

	public void setTimeSpent(Float timeSpent) {
		this.timeSpent = timeSpent;
	}

	public String getImportantFlag() {
		return this.importantFlag;
	}

	public void setImportantFlag(String importantFlag) {
		this.importantFlag = importantFlag;
	}

}
