package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * IndividualCasesHistories generated by hbm2java
 * 
 * @author Kim To
 */
public class IndividualCasesHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer caseId;
	private Integer clientId;
	private Integer advocateId;
	private Integer caseStatusId;
	private String description;
	private Integer priorityId;
	private Integer serviceProviderId;
	private String referredTo;
	private Integer oldCaseId;
	private Integer relatedEnquiryId;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public IndividualCasesHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param caseId
	 * @param clientId
	 * @param advocateId
	 * @param caseStatusId
	 * @param description
	 * @param priorityId
	 * @param serviceProviderId
	 * @param referredTo
	 * @param oldCaseId
	 * @param relatedEnquiryId
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public IndividualCasesHistories(Integer id, String action, Integer caseId,
			Integer clientId, Integer advocateId, Integer caseStatusId,
			String description, Integer priorityId, Integer serviceProviderId,
			String referredTo, Integer oldCaseId, Integer relatedEnquiryId,
			Integer changeOrder, Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.caseId = caseId;
		this.clientId = clientId;
		this.advocateId = advocateId;
		this.caseStatusId = caseStatusId;
		this.description = description;
		this.priorityId = priorityId;
		this.serviceProviderId = serviceProviderId;
		this.referredTo = referredTo;
		this.oldCaseId = oldCaseId;
		this.relatedEnquiryId = relatedEnquiryId;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the caseId
	 */
	public Integer getCaseId() {
		return this.caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the clientId
	 */
	public Integer getClientId() {
		return this.clientId;
	}

	/**
	 * @param clientId the clientId to set
	 */
	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	/**
	 * @return the advocateId
	 */
	public Integer getAdvocateId() {
		return this.advocateId;
	}

	/**
	 * @param advocateId the advocateId to set
	 */
	public void setAdvocateId(Integer advocateId) {
		this.advocateId = advocateId;
	}

	/**
	 * @return the caseStatusId
	 */
	public Integer getCaseStatusId() {
		return this.caseStatusId;
	}

	/**
	 * @param caseStatusId the caseStatusId to set
	 */
	public void setCaseStatusId(Integer caseStatusId) {
		this.caseStatusId = caseStatusId;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the priorityId
	 */
	public Integer getPriorityId() {
		return this.priorityId;
	}

	/**
	 * @param priorityId the priorityId to set
	 */
	public void setPriorityId(Integer priorityId) {
		this.priorityId = priorityId;
	}

	/**
	 * @return the serviceProviderId
	 */
	public Integer getServiceProviderId() {
		return this.serviceProviderId;
	}

	/**
	 * @param serviceProviderId the serviceProviderId to set
	 */
	public void setServiceProviderId(Integer serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	/**
	 * @return the referredTo
	 */
	public String getReferredTo() {
		return this.referredTo;
	}

	/**
	 * @param referredTo the referredTo to set
	 */
	public void setReferredTo(String referredTo) {
		this.referredTo = referredTo;
	}

	/**
	 * @return the oldCaseId
	 */
	public Integer getOldCaseId() {
		return this.oldCaseId;
	}

	/**
	 * @param oldCaseId the oldCaseId to set
	 */
	public void setOldCaseId(Integer oldCaseId) {
		this.oldCaseId = oldCaseId;
	}

	/**
	 * @return the relatedEnquiryId
	 */
	public Integer getRelatedEnquiryId() {
		return this.relatedEnquiryId;
	}

	/**
	 * @param relatedEnquiryId the relatedEnquiryId to set
	 */
	public void setRelatedEnquiryId(Integer relatedEnquiryId) {
		this.relatedEnquiryId = relatedEnquiryId;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return this.changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
