package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * IndividualCases generated by hbm2java
 */
public class IndividualCases implements java.io.Serializable {

	private Integer id;
//	private Integer clientId;
	private Contacts contact;
	private Integer advocateId;
	private Integer caseStatusId;
	private String description;
//	private Integer priorityId;
	private PriorityTypes priorityType;
	private Integer serviceProviderId;
	private Date createdDateTime;
	private Integer createdUserId;
	private Date updatedDateTime;
	private Integer updatedUserId;
	private String referredTo;
//	private Integer oldCaseId;
	private Set<Risks> risksSet = new HashSet<Risks>();
	private IndividualCases oldCase;
	private Set<IndividualCases> individualCasesSet = new HashSet<IndividualCases>();
	private Set<CaseIssues> caseIssuesSet = new HashSet<CaseIssues>();

	/**
	 * @param id
	 * @param contact
	 * @param advocateId
	 * @param caseStatusId
	 * @param description
	 * @param priorityType
	 * @param serviceProviderId
	 * @param createdDateTime
	 * @param createdUserId
	 * @param updatedDateTime
	 * @param updatedUserId
	 * @param referredTo
	 * @param risksSet
	 * @param individualCase
	 * @param individualCasesSet
	 */
	public IndividualCases(Integer id, Contacts contact, Integer advocateId,
			Integer caseStatusId, String description,
			PriorityTypes priorityType, Integer serviceProviderId,
			Date createdDateTime, Integer createdUserId, Date updatedDateTime,
			Integer updatedUserId, String referredTo, Set<Risks> risksSet,
			IndividualCases oldCase,
			Set<IndividualCases> individualCasesSet) {
		this.id = id;
		this.contact = contact;
		this.advocateId = advocateId;
		this.caseStatusId = caseStatusId;
		this.description = description;
		this.priorityType = priorityType;
		this.serviceProviderId = serviceProviderId;
		this.createdDateTime = createdDateTime;
		this.createdUserId = createdUserId;
		this.updatedDateTime = updatedDateTime;
		this.updatedUserId = updatedUserId;
		this.referredTo = referredTo;
		this.risksSet = risksSet;
		this.oldCase = oldCase;
		this.individualCasesSet = individualCasesSet;
	}

	public IndividualCases() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	public Integer getClientId() {
//		return this.clientId;
//	}
//
//	public void setClientId(Integer clientId) {
//		this.clientId = clientId;
//	}

	/**
	 * @return the contact
	 */
	public Contacts getContact() {
		return this.contact;
	}

	/**
	 * @param contact the contact to set
	 */
	public void setContact(Contacts contact) {
		this.contact = contact;
	}

	public Integer getAdvocateId() {
		return this.advocateId;
	}

	public void setAdvocateId(Integer advocateId) {
		this.advocateId = advocateId;
	}

	public Integer getCaseStatusId() {
		return this.caseStatusId;
	}

	public void setCaseStatusId(Integer caseStatusId) {
		this.caseStatusId = caseStatusId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

//	public Integer getPriorityId() {
//		return this.priorityId;
//	}
//
//	public void setPriorityId(Integer priorityId) {
//		this.priorityId = priorityId;
//	}

	public Integer getServiceProviderId() {
		return this.serviceProviderId;
	}

	/**
	 * @return the priorityType
	 */
	public PriorityTypes getPriorityType() {
		return priorityType;
	}

	/**
	 * @param priorityType the priorityType to set
	 */
	public void setPriorityType(PriorityTypes priorityType) {
		this.priorityType = priorityType;
	}

	public void setServiceProviderId(Integer serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	public Integer getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Integer updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public String getReferredTo() {
		return this.referredTo;
	}

	public void setReferredTo(String referredTo) {
		this.referredTo = referredTo;
	}

//	public Integer getOldCaseId() {
//		return this.oldCaseId;
//	}
//
//	public void setOldCaseId(Integer oldCaseId) {
//		this.oldCaseId = oldCaseId;
//	}

	/**
	 * @return the risksSet
	 */
	public Set<Risks> getRisksSet() {
		return this.risksSet;
	}

	/**
	 * @param risksSet the risksSet to set
	 */
	public void setRisksSet(Set<Risks> risksSet) {
		this.risksSet = risksSet;
	}

	/**
	 * @return the individualCase
	 */
	public IndividualCases getOldCase() {
		return this.oldCase;
	}

	/**
	 * @param individualCase the individualCase to set
	 */
	public void setOldCase(IndividualCases oldCase) {
		this.oldCase = oldCase;
	}

	/**
	 * @return the individualCasesSet
	 */
	public Set<IndividualCases> getIndividualCasesSet() {
		return this.individualCasesSet;
	}

	/**
	 * @param individualCasesSet the individualCasesSet to set
	 */
	public void setIndividualCasesSet(Set<IndividualCases> individualCasesSet) {
		this.individualCasesSet = individualCasesSet;
	}

	/**
	 * @return the caseIssuesSet
	 */
	public Set<CaseIssues> getCaseIssuesSet() {
		return this.caseIssuesSet;
	}

	/**
	 * @param caseIssuesSet the caseIssuesSet to set
	 */
	public void setCaseIssuesSet(Set<CaseIssues> caseIssuesSet) {
		this.caseIssuesSet = caseIssuesSet;
	}

}
