package uow.ia.bean;

import java.util.HashSet;
import java.util.Set;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * IssueTypes generated by hbm2java
 */
public class IssueTypes implements java.io.Serializable {

	private Integer id;
	private String issueName;
	private String issueDescription;
	private Set<EnquiryIssues> enquiryIssuesSet = new HashSet<EnquiryIssues>();
	private Set<CaseIssues> caseIssuesSet = new HashSet<CaseIssues>();


	/**
	 * 
	 */
	public IssueTypes() {
		// TODO Auto-generated constructor stub
	}


	/**
	 * @param id
	 * @param issueName
	 * @param issueDescription
	 * @param enquiryIssuesSet
	 * @param caseIssuesSet
	 */
	public IssueTypes(Integer id, String issueName, String issueDescription,
			Set<EnquiryIssues> enquiryIssuesSet, Set<CaseIssues> caseIssuesSet) {
		this.id = id;
		this.issueName = issueName;
		this.issueDescription = issueDescription;
		this.enquiryIssuesSet = enquiryIssuesSet;
		this.caseIssuesSet = caseIssuesSet;
	}


	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the issueName
	 */
	public String getIssueName() {
		return this.issueName;
	}

	/**
	 * @param issueName the issueName to set
	 */
	public void setIssueName(String issueName) {
		this.issueName = issueName;
	}

	/**
	 * @return the issueDescription
	 */
	public String getIssueDescription() {
		return this.issueDescription;
	}

	/**
	 * @param issueDescription the issueDescription to set
	 */
	public void setIssueDescription(String issueDescription) {
		this.issueDescription = issueDescription;
	}


	/**
	 * @return the enquiryIssuesSet
	 */
	public Set<EnquiryIssues> getEnquiryIssuesSet() {
		return this.enquiryIssuesSet;
	}


	/**
	 * @param enquiryIssuesSet the enquiryIssuesSet to set
	 */
	public void setEnquiryIssuesSet(Set<EnquiryIssues> enquiryIssuesSet) {
		this.enquiryIssuesSet = enquiryIssuesSet;
	}


	/**
	 * @return the caseIssuesSet
	 */
	public Set<CaseIssues> getCaseIssuesSet() {
		return this.caseIssuesSet;
	}


	/**
	 * @param caseIssuesSet the caseIssuesSet to set
	 */
	public void setCaseIssuesSet(Set<CaseIssues> caseIssuesSet) {
		this.caseIssuesSet = caseIssuesSet;
	}

}
