package uow.ia.bean;

import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * Messages generated by hbm2java
 */

@Indexed
public class Messages implements java.io.Serializable {

	@DocumentId
	private Integer id;
	
	@Field
	private String messageName;
	
	@Field
	private String messages;
	
	@Field
	private String description;

	public Messages() {
	}

	public Messages(String messageName, String messages, String description) {
		this.messageName = messageName;
		this.messages = messages;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMessageName() {
		return this.messageName;
	}

	public void setMessageName(String messageName) {
		this.messageName = messageName;
	}

	public String getMessages() {
		return this.messages;
	}

	public void setMessages(String messages) {
		this.messages = messages;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
