package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * PlansHistories generated by hbm2java
 * 
 * @author Kim To
 * @version 1.0.1, 28/09/2014
 * 
 * Modification History:
 * 		28/09/2014	Mods to match table structure
 */
public class PlansHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer caseId;
	private Integer statusId;
	private Date closedDateTime;
	private Date lastReviewedDate;
	private Integer reviewFrequencyId;
	private Date providedPlanDate;
	private Date consentSignedDate;
	private Integer supportPersonId;
	private Integer authorisedById;
	private Date authorisedByDate;
	private String notes;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public PlansHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param caseId
	 * @param statusId
	 * @param closedDateTime
	 * @param lastReviewedDate
	 * @param reviewFrequencyId
	 * @param providedPlanDate
	 * @param consentSignedDate
	 * @param supportPersonId
	 * @param authorisedById
	 * @param authorisedByDate
	 * @param notes
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public PlansHistories(Integer id, String action, Integer caseId,
			Integer statusId, Date closedDateTime, Date lastReviewedDate,
			Integer reviewFrequencyId, Date providedPlanDate,
			Date consentSignedDate, Integer supportPersonId,
			Integer authorisedById, Date authorisedByDate, String notes,
			Integer changeOrder, Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.caseId = caseId;
		this.statusId = statusId;
		this.closedDateTime = closedDateTime;
		this.lastReviewedDate = lastReviewedDate;
		this.reviewFrequencyId = reviewFrequencyId;
		this.providedPlanDate = providedPlanDate;
		this.consentSignedDate = consentSignedDate;
		this.supportPersonId = supportPersonId;
		this.authorisedById = authorisedById;
		this.authorisedByDate = authorisedByDate;
		this.notes = notes;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the caseId
	 */
	public Integer getCaseId() {
		return this.caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the statusId
	 */
	public Integer getStatusId() {
		return this.statusId;
	}

	/**
	 * @param statusId the statusId to set
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * @return the closedDateTime
	 */
	public Date getClosedDateTime() {
		return this.closedDateTime;
	}

	/**
	 * @param closedDateTime the closedDateTime to set
	 */
	public void setClosedDateTime(Date closedDateTime) {
		this.closedDateTime = closedDateTime;
	}

	/**
	 * @return the lastReviewedDate
	 */
	public Date getLastReviewedDate() {
		return this.lastReviewedDate;
	}

	/**
	 * @param lastReviewedDate the lastReviewedDate to set
	 */
	public void setLastReviewedDate(Date lastReviewedDate) {
		this.lastReviewedDate = lastReviewedDate;
	}

	/**
	 * @return the reviewFrequencyId
	 */
	public Integer getReviewFrequencyId() {
		return this.reviewFrequencyId;
	}

	/**
	 * @param reviewFrequencyId the reviewFrequencyId to set
	 */
	public void setReviewFrequencyId(Integer reviewFrequencyId) {
		this.reviewFrequencyId = reviewFrequencyId;
	}

	/**
	 * @return the providedPlanDate
	 */
	public Date getProvidedPlanDate() {
		return this.providedPlanDate;
	}

	/**
	 * @param providedPlanDate the providedPlanDate to set
	 */
	public void setProvidedPlanDate(Date providedPlanDate) {
		this.providedPlanDate = providedPlanDate;
	}

	/**
	 * @return the consentSignedDate
	 */
	public Date getConsentSignedDate() {
		return this.consentSignedDate;
	}

	/**
	 * @param consentSignedDate the consentSignedDate to set
	 */
	public void setConsentSignedDate(Date consentSignedDate) {
		this.consentSignedDate = consentSignedDate;
	}

	/**
	 * @return the supportPersonId
	 */
	public Integer getSupportPersonId() {
		return this.supportPersonId;
	}

	/**
	 * @param supportPersonId the supportPersonId to set
	 */
	public void setSupportPersonId(Integer supportPersonId) {
		this.supportPersonId = supportPersonId;
	}

	/**
	 * @return the authorisedById
	 */
	public Integer getAuthorisedById() {
		return this.authorisedById;
	}

	/**
	 * @param authorisedById the authorisedById to set
	 */
	public void setAuthorisedById(Integer authorisedById) {
		this.authorisedById = authorisedById;
	}

	/**
	 * @return the authorisedByDate
	 */
	public Date getAuthorisedByDate() {
		return this.authorisedByDate;
	}

	/**
	 * @param authorisedByDate the authorisedByDate to set
	 */
	public void setAuthorisedByDate(Date authorisedByDate) {
		this.authorisedByDate = authorisedByDate;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return this.notes;
	}

	/**
	 * @param notes the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return this.changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
