package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * PlanDevelopersHistories generated by hbm2java
 */
public class PlanDevelopersHistories implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private int developerId;
	private String action;
	private Integer planId;
	private Integer contactId;
	private int createdUserId;

	public PlanDevelopersHistories() {
	}

	public PlanDevelopersHistories(int developerId, String action,
			int createdUserId) {
		this.developerId = developerId;
		this.action = action;
		this.createdUserId = createdUserId;
	}

	public PlanDevelopersHistories(int developerId, String action,
			Integer planId, Integer contactId, int createdUserId) {
		this.developerId = developerId;
		this.action = action;
		this.planId = planId;
		this.contactId = contactId;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getDeveloperId() {
		return this.developerId;
	}

	public void setDeveloperId(int developerId) {
		this.developerId = developerId;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Integer getPlanId() {
		return this.planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public int getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(int createdUserId) {
		this.createdUserId = createdUserId;
	}

}
