package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Plans generated by hbm2java
 */
public class Plans implements java.io.Serializable {

	private Integer id;
	private Integer caseId;
	private Integer statusId;
	private Date createdDateTime;
	private Date closedDateTime;
	private Date lastReviewedDate;
	private Integer reviewFrequencyId;
	private Date providedPlanDate;
	private Date consentSignedDate;
	private Integer supportPersonId;
	private Integer authorisedById;
	private Date authorisedByDate;
	private String notes;
	private Date updatedDateTime;
	private Integer updatedUserId;
	private Integer createdUserId;

	public Plans() {
	}

	public Plans(Integer caseId, Integer statusId, Date createdDateTime,
			Date closedDateTime, Date lastReviewedDate,
			Integer reviewFrequencyId, Date providedPlanDate,
			Date consentSignedDate, Integer supportPersonId,
			Integer authorisedById, Date authorisedByDate, String notes,
			Date updatedDateTime, Integer updatedUserId, Integer createdUserId) {
		this.caseId = caseId;
		this.statusId = statusId;
		this.createdDateTime = createdDateTime;
		this.closedDateTime = closedDateTime;
		this.lastReviewedDate = lastReviewedDate;
		this.reviewFrequencyId = reviewFrequencyId;
		this.providedPlanDate = providedPlanDate;
		this.consentSignedDate = consentSignedDate;
		this.supportPersonId = supportPersonId;
		this.authorisedById = authorisedById;
		this.authorisedByDate = authorisedByDate;
		this.notes = notes;
		this.updatedDateTime = updatedDateTime;
		this.updatedUserId = updatedUserId;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public Date getClosedDateTime() {
		return this.closedDateTime;
	}

	public void setClosedDateTime(Date closedDateTime) {
		this.closedDateTime = closedDateTime;
	}

	public Date getLastReviewedDate() {
		return this.lastReviewedDate;
	}

	public void setLastReviewedDate(Date lastReviewedDate) {
		this.lastReviewedDate = lastReviewedDate;
	}

	public Integer getReviewFrequencyId() {
		return this.reviewFrequencyId;
	}

	public void setReviewFrequencyId(Integer reviewFrequencyId) {
		this.reviewFrequencyId = reviewFrequencyId;
	}

	public Date getProvidedPlanDate() {
		return this.providedPlanDate;
	}

	public void setProvidedPlanDate(Date providedPlanDate) {
		this.providedPlanDate = providedPlanDate;
	}

	public Date getConsentSignedDate() {
		return this.consentSignedDate;
	}

	public void setConsentSignedDate(Date consentSignedDate) {
		this.consentSignedDate = consentSignedDate;
	}

	public Integer getSupportPersonId() {
		return this.supportPersonId;
	}

	public void setSupportPersonId(Integer supportPersonId) {
		this.supportPersonId = supportPersonId;
	}

	public Integer getAuthorisedById() {
		return this.authorisedById;
	}

	public void setAuthorisedById(Integer authorisedById) {
		this.authorisedById = authorisedById;
	}

	public Date getAuthorisedByDate() {
		return this.authorisedByDate;
	}

	public void setAuthorisedByDate(Date authorisedByDate) {
		this.authorisedByDate = authorisedByDate;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	public Integer getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Integer updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

}
