package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * PlanGoalsHistories generated by hbm2java
 * 
 * @author Kim To
 * @version 1.0.1, 28/09/2014
 * 
 * Modification History:
 * 		28/09/2014	Mods to match table structure
 */
public class PlanGoalsHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer planGoalId;
	private Integer caseId;
	private Integer goalTypeId;
	private Date completionDateTime;
	private String goalDescription;
	private String goalAction;
	private Integer statusId;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public PlanGoalsHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param planGoalId
	 * @param caseId
	 * @param goalTypeId
	 * @param completionDateTime
	 * @param goalDescription
	 * @param goalAction
	 * @param statusId
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public PlanGoalsHistories(Integer id, String action, Integer planGoalId,
			Integer caseId, Integer goalTypeId, Date completionDateTime,
			String goalDescription, String goalAction, Integer statusId,
			Integer changeOrder, Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.planGoalId = planGoalId;
		this.caseId = caseId;
		this.goalTypeId = goalTypeId;
		this.completionDateTime = completionDateTime;
		this.goalDescription = goalDescription;
		this.goalAction = goalAction;
		this.statusId = statusId;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the planGoalId
	 */
	public Integer getPlanGoalId() {
		return this.planGoalId;
	}

	/**
	 * @param planGoalId the planGoalId to set
	 */
	public void setPlanGoalId(Integer planGoalId) {
		this.planGoalId = planGoalId;
	}

	/**
	 * @return the caseId
	 */
	public Integer getCaseId() {
		return this.caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the goalTypeId
	 */
	public Integer getGoalTypeId() {
		return this.goalTypeId;
	}

	/**
	 * @param goalTypeId the goalTypeId to set
	 */
	public void setGoalTypeId(Integer goalTypeId) {
		this.goalTypeId = goalTypeId;
	}

	/**
	 * @return the completionDateTime
	 */
	public Date getCompletionDateTime() {
		return this.completionDateTime;
	}

	/**
	 * @param completionDateTime the completionDateTime to set
	 */
	public void setCompletionDateTime(Date completionDateTime) {
		this.completionDateTime = completionDateTime;
	}

	/**
	 * @return the goalDescription
	 */
	public String getGoalDescription() {
		return this.goalDescription;
	}

	/**
	 * @param goalDescription the goalDescription to set
	 */
	public void setGoalDescription(String goalDescription) {
		this.goalDescription = goalDescription;
	}

	/**
	 * @return the goalAction
	 */
	public String getGoalAction() {
		return this.goalAction;
	}

	/**
	 * @param goalAction the goalAction to set
	 */
	public void setGoalAction(String goalAction) {
		this.goalAction = goalAction;
	}

	/**
	 * @return the statusId
	 */
	public Integer getStatusId() {
		return this.statusId;
	}

	/**
	 * @param statusId the statusId to set
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return this.changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}


}
