package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PlansHistories generated by hbm2java
 */
public class PlansHistories implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private int planId;
	private String action;
	private int changeOrder;
	private Integer statusId;
	private Date closedDate;
	private Date lastReviewedDate;
	private Integer reviewFrequencyId;
	private Date providedPlanDate;
	private Date consentSignedDate;
	private Integer supportPersonId;
	private Integer authorisedById;
	private Date authorisedByDate;
	private String notes;
	private Integer createdUserId;

	public PlansHistories() {
	}

	public PlansHistories(int planId, String action, int changeOrder) {
		this.planId = planId;
		this.action = action;
		this.changeOrder = changeOrder;
	}

	public PlansHistories(int planId, String action, int changeOrder,
			Integer statusId, Date closedDate, Date lastReviewedDate,
			Integer reviewFrequencyId, Date providedPlanDate,
			Date consentSignedDate, Integer supportPersonId,
			Integer authorisedById, Date authorisedByDate, String notes,
			Integer createdUserId) {
		this.planId = planId;
		this.action = action;
		this.changeOrder = changeOrder;
		this.statusId = statusId;
		this.closedDate = closedDate;
		this.lastReviewedDate = lastReviewedDate;
		this.reviewFrequencyId = reviewFrequencyId;
		this.providedPlanDate = providedPlanDate;
		this.consentSignedDate = consentSignedDate;
		this.supportPersonId = supportPersonId;
		this.authorisedById = authorisedById;
		this.authorisedByDate = authorisedByDate;
		this.notes = notes;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getPlanId() {
		return this.planId;
	}

	public void setPlanId(int planId) {
		this.planId = planId;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public int getChangeOrder() {
		return this.changeOrder;
	}

	public void setChangeOrder(int changeOrder) {
		this.changeOrder = changeOrder;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	public Date getLastReviewedDate() {
		return this.lastReviewedDate;
	}

	public void setLastReviewedDate(Date lastReviewedDate) {
		this.lastReviewedDate = lastReviewedDate;
	}

	public Integer getReviewFrequencyId() {
		return this.reviewFrequencyId;
	}

	public void setReviewFrequencyId(Integer reviewFrequencyId) {
		this.reviewFrequencyId = reviewFrequencyId;
	}

	public Date getProvidedPlanDate() {
		return this.providedPlanDate;
	}

	public void setProvidedPlanDate(Date providedPlanDate) {
		this.providedPlanDate = providedPlanDate;
	}

	public Date getConsentSignedDate() {
		return this.consentSignedDate;
	}

	public void setConsentSignedDate(Date consentSignedDate) {
		this.consentSignedDate = consentSignedDate;
	}

	public Integer getSupportPersonId() {
		return this.supportPersonId;
	}

	public void setSupportPersonId(Integer supportPersonId) {
		this.supportPersonId = supportPersonId;
	}

	public Integer getAuthorisedById() {
		return this.authorisedById;
	}

	public void setAuthorisedById(Integer authorisedById) {
		this.authorisedById = authorisedById;
	}

	public Date getAuthorisedByDate() {
		return this.authorisedByDate;
	}

	public void setAuthorisedByDate(Date authorisedByDate) {
		this.authorisedByDate = authorisedByDate;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

}
