package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * PlanDevelopersHistories generated by hbm2java
 * 
 * @author Kim To
 * @version 1.0.1, 28/09/2014
 * 
 * Modification History:
 * 		Mods to bean structure to match table structure 
 */
public class PlanDevelopersHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer planDeveloperId;
	private Integer caseId;
	private Integer contactId;
	private Integer changeOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public PlanDevelopersHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param planDeveloperId
	 * @param planId
	 * @param contactId
	 * @param changeOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public PlanDevelopersHistories(Integer id, String action,
			Integer planDeveloperId, Integer caseId, Integer contactId,
			Integer changeOrder, Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.planDeveloperId = planDeveloperId;
		this.caseId = caseId;
		this.contactId = contactId;
		this.changeOrder = changeOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the planDeveloperId
	 */
	public Integer getPlanDeveloperId() {
		return this.planDeveloperId;
	}

	/**
	 * @param planDeveloperId the planDeveloperId to set
	 */
	public void setPlanDeveloperId(Integer planDeveloperId) {
		this.planDeveloperId = planDeveloperId;
	}

	/**
	 * @return the caseId
	 */
	public Integer getCaseId() {
		return caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the contactId
	 */
	public Integer getContactId() {
		return this.contactId;
	}

	/**
	 * @param contactId the contactId to set
	 */
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	/**
	 * @return the changeOrder
	 */
	public Integer getChangeOrder() {
		return this.changeOrder;
	}

	/**
	 * @param changeOrder the changeOrder to set
	 */
	public void setChangeOrder(Integer changeOrder) {
		this.changeOrder = changeOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}


}
