package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * PriorityTypes generated by hbm2java
 */
public class PriorityTypes implements java.io.Serializable {

	private Integer id;
	private String priorityName;

	public PriorityTypes() {
	}

	public PriorityTypes(String priorityName) {
		this.priorityName = priorityName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPriorityName() {
		return this.priorityName;
	}

	public void setPriorityName(String priorityName) {
		this.priorityName = priorityName;
	}

}
