package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Reminders generated by hbm2java
 */
public class Reminders implements java.io.Serializable {

	private Integer id;
	private Integer eventId;
	private Date reminderDate;
	private Date startTime;

	public Reminders() {
	}

	public Reminders(Integer eventId, Date reminderDate, Date startTime) {
		this.eventId = eventId;
		this.reminderDate = reminderDate;
		this.startTime = startTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public Date getReminderDate() {
		return this.reminderDate;
	}

	public void setReminderDate(Date reminderDate) {
		this.reminderDate = reminderDate;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

}
