package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * ReviewFrequencies generated by hbm2java
 */
public class ReviewFrequencies implements java.io.Serializable {

	private Integer id;
	private String frequencyName;

	public ReviewFrequencies() {
	}

	public ReviewFrequencies(String frequencyName) {
		this.frequencyName = frequencyName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFrequencyName() {
		return this.frequencyName;
	}

	public void setFrequencyName(String frequencyName) {
		this.frequencyName = frequencyName;
	}

}
