package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * RisksHistories generated by hbm2java
 * 
 * @author Kim To
 * @version 1.0.1, 28/09/2014
 * 
 * Modification History:
 * 		Change to map to table correctly
 */
public class RisksHistories implements java.io.Serializable {

	private Integer id;
	private String action;
	private Integer riskId;
	private String riskDescription;
	private String riskManagement;
	private Integer caseId;
	private Integer changerOrder;
	private Integer createdUserId;
	private Date createdDateTime;

	public RisksHistories() {
	}

	/**
	 * @param id
	 * @param action
	 * @param riskId
	 * @param riskDescription
	 * @param riskManagement
	 * @param caseId
	 * @param changerOrder
	 * @param createdUserId
	 * @param createdDateTime
	 */
	public RisksHistories(Integer id, String action, Integer riskId,
			String riskDescription, String riskManagement, Integer caseId,
			Integer changerOrder, Integer createdUserId, Date createdDateTime) {
		this.id = id;
		this.action = action;
		this.riskId = riskId;
		this.riskDescription = riskDescription;
		this.riskManagement = riskManagement;
		this.caseId = caseId;
		this.changerOrder = changerOrder;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return this.action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the riskId
	 */
	public Integer getRiskId() {
		return this.riskId;
	}

	/**
	 * @param riskId the riskId to set
	 */
	public void setRiskId(Integer riskId) {
		this.riskId = riskId;
	}

	/**
	 * @return the riskDescription
	 */
	public String getRiskDescription() {
		return this.riskDescription;
	}

	/**
	 * @param riskDescription the riskDescription to set
	 */
	public void setRiskDescription(String riskDescription) {
		this.riskDescription = riskDescription;
	}

	/**
	 * @return the riskManagement
	 */
	public String getRiskManagement() {
		return this.riskManagement;
	}

	/**
	 * @param riskManagement the riskManagement to set
	 */
	public void setRiskManagement(String riskManagement) {
		this.riskManagement = riskManagement;
	}

	/**
	 * @return the caseId
	 */
	public Integer getCaseId() {
		return this.caseId;
	}

	/**
	 * @param caseId the caseId to set
	 */
	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	/**
	 * @return the changerOrder
	 */
	public Integer getChangerOrder() {
		return this.changerOrder;
	}

	/**
	 * @param changerOrder the changerOrder to set
	 */
	public void setChangerOrder(Integer changerOrder) {
		this.changerOrder = changerOrder;
	}

	/**
	 * @return the createdUserId
	 */
	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	/**
	 * @param createdUserId the createdUserId to set
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * @return the createdDateTime
	 */
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	/**
	 * @param createdDateTime the createdDateTime to set
	 */
	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

}
