package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

import java.sql.Date;

/**
 * RisksHistories generated by hbm2java
 */
public class RisksHistories implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private int riskId;
	private String action;
	private String oldRiskDescription;
	private String newRiskDescription;
	private String oldRiskManagement;
	private String newRiskManagement;
	private Integer caseId;
	private int createdUserId;

	public RisksHistories() {
	}

	public RisksHistories(int riskId, String action, int createdUserId) {
		this.riskId = riskId;
		this.action = action;
		this.createdUserId = createdUserId;
	}

	public RisksHistories(int riskId, String action, String oldRiskDescription,
			String newRiskDescription, String oldRiskManagement,
			String newRiskManagement, Integer caseId, int createdUserId) {
		this.riskId = riskId;
		this.action = action;
		this.oldRiskDescription = oldRiskDescription;
		this.newRiskDescription = newRiskDescription;
		this.oldRiskManagement = oldRiskManagement;
		this.newRiskManagement = newRiskManagement;
		this.caseId = caseId;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getRiskId() {
		return this.riskId;
	}

	public void setRiskId(int riskId) {
		this.riskId = riskId;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getOldRiskDescription() {
		return this.oldRiskDescription;
	}

	public void setOldRiskDescription(String oldRiskDescription) {
		this.oldRiskDescription = oldRiskDescription;
	}

	public String getNewRiskDescription() {
		return this.newRiskDescription;
	}

	public void setNewRiskDescription(String newRiskDescription) {
		this.newRiskDescription = newRiskDescription;
	}

	public String getOldRiskManagement() {
		return this.oldRiskManagement;
	}

	public void setOldRiskManagement(String oldRiskManagement) {
		this.oldRiskManagement = oldRiskManagement;
	}

	public String getNewRiskManagement() {
		return this.newRiskManagement;
	}

	public void setNewRiskManagement(String newRiskManagement) {
		this.newRiskManagement = newRiskManagement;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public int getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(int createdUserId) {
		this.createdUserId = createdUserId;
	}

}
