package uow.ia.bean;

import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * Roles generated by hbm2java
 */

@Indexed
public class Roles implements java.io.Serializable {

	@DocumentId
	private Integer id;
	
	@Field
	private String role;

	public Roles() {
	}

	public Roles(String role) {
		this.role = role;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
