package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * StatusTypes generated by hbm2java
 */
public class StatusTypes implements java.io.Serializable {

	private Integer id;
	private String statusName;

	public StatusTypes() {
	}

	public StatusTypes(String statusName) {
		this.statusName = statusName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
