package uow.ia.bean;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * TitleTypes generated by hbm2java
 */
public class TitleTypes implements java.io.Serializable {

	private Integer id;
	private String name;

	public TitleTypes() {
	}

	public TitleTypes(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
