package uow.ia.bean;

import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;

// Generated Aug 9, 2014 1:06:20 PM by Hibernate Tools 4.0.0

/**
 * TitleTypes generated by hbm2java
 * 
 * @author Kim To
 * @version 1.0.1, 09/09/2014
 */

@Indexed
public class TitleTypes implements java.io.Serializable {
	@DocumentId
	private Integer id;
	
	@Field
	private String name;

	public TitleTypes() {
	}

	public TitleTypes(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String toString() {
		return this.id + ": " + this.name;
	}

}
